/* Allegro datafile object indexes, produced by grabber v3.0 */
/* Datafile: c:\mydocu~1\dan\hangman\hangman.dat */
/* Date: Tue May 26 19:27:06 1998 */
/* Do not hand edit! */

#define ADDPART_WAV                      0        /* SAMP */
#define ALPHABACK_PIC                    1        /* BMP  */
#define ANSWERBACK_PIC                   2        /* BMP  */
#define BANG_WAV                         3        /* SAMP */
#define BIG_FONT                         4        /* FONT */
#define CATEGBACK_PIC                    5        /* BMP  */
#define CATEGORY1_PIC                    6        /* BMP  */
#define CATEGORY2_PIC                    7        /* BMP  */
#define CATEGORY3_PIC                    8        /* BMP  */
#define CATEGORY4_PIC                    9        /* BMP  */
#define CATEGORY5_PIC                    10       /* BMP  */
#define DEAD_MID                         11       /* MIDI */
#define DEADBACK_PIC                     12       /* BMP  */
#define FLICBACK_PIC                     13       /* BMP  */
#define GAMEBACK_PIC                     14       /* BMP  */
#define GAMESCREEN_PAL                   15       /* PAL  */
#define INSTRUCT_TXT                     16       /* TXT  */
#define WORDS1_TXT                       17       /* TXT  */
#define WORDS2_TXT                       18       /* TXT  */
#define WORDS3_TXT                       19       /* TXT  */
#define WORDS4_TXT                       20       /* TXT  */
#define WORDS5_TXT                       21       /* TXT  */

